### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by epka** [atfzl/obsidian-apple-books-plugin#2]
Hi, great idea, but I don't seem to get this working.
No sync happens.

MacOS: 13.2.1
Books: 5.1
Obsidian: 1.1.16

Also, can't enable plug-in on iPad. Not intended to work on iPadOS?

**Comment by emory** [comment]
i have it pull and get one annotation but the Readwise bridge hauls all of them over just fine and i don't know how to troubleshoot this considering the gymnastics involved to extract anything out of an Apple macOS application

**Comment by epka** [comment]
Apple Books is a mess anyways: I have books in iCloud syncing with iPad and annotations don't sync all too well either, so maybe it's that? 
On the other hand, tried app Klib, and it pulls the annotations allright from same location as apple-books-plugin probes.

**Comment by atfzl** [comment]
This plugin only works on mac and not on iPad. It could be the case that you haven't opened Apple Books for highlights to sync to the local database. Could you first confirm that the highlights are visible in Apple Books and then try syncing the highlights to obsidian.

**Comment by epka** [comment]
yes, annotations are visible on Books. Made fresh ones, quit open Books etc. Also installed the plugin on fresh vault. 

As said, trying with Klib app, manages to pull annotations, and I would imagine it also polls the local database.

**Comment by jancbeck** [comment]
Same issue for me. Installed it on Mac but nothing happens.

**Comment by atfzl** [comment]
Should be fixed by https://github.com/atfzl/obsidian-apple-books-plugin/commit/3d702d4fded1e5fd74e7aaad5984f25b245cef04 released in v1.0.1, please verify.

**Comment by epka** [comment]
Works now ! Thanks. Does not sync Notes, right?

**Comment by jancbeck** [comment]
Can confirm, it syncing works now. Thanks!

**Comment by atfzl** [comment]
@epka What do you mean by "Does not sync Notes"?

**Comment by epka** [comment]
@atfzl I mean using 'Add note' -annotation. Just testing now and highlights sync ok.
But if I select text on Books, and then 'Add note', insert some text on note: 
- Books highlights the selected text and then attach note on it (on which I can write my own notes).
- It syncs on Obsidian as highlight (the highlighted text syncs, but not the text from note)

**Comment by atfzl** [comment]
Yes, the plugin does not sync notes from Apple Books.

**Comment by atfzl** [comment]
Fixed in https://github.com/atfzl/obsidian-apple-books-plugin/commit/3d702d4fded1e5fd74e7aaad5984f25b245cef04 released in v1.0.1
