### ISSUE TITLE
Deletes the folder you specify for highlights if it already exists

### ISSUE THREAD

**Issue by mrowe** [atfzl/obsidian-apple-books-plugin#3]
This is not cool:
https://github.com/atfzl/obsidian-apple-books-plugin/blob/36aad0fb0660a51032f758a03469caf9835e4885/main.ts#L186

This silently deleted my existing folder full of Kindle highlights and additional notes, without warning.

I don't think this plugin should assume it is the only thing using that folder!

**Comment by atfzl** [comment]
Fixed in #4
